name: Pull request on main

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    if: ${{ github.repository == 'ash1khan/digital-garden'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Get bun version
        id: bun
        run: |
          echo "version=$(bun --version)" >> "$GITHUB_OUTPUT"

      - name: Set caching
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/bun.lockb') }}-${{ steps.bun.outputs.version }}

      - name: Install dependencies
        run: bun install

      - name: Ensuring Astro builds with bun
        run: bun run build

      # TODO: add appropriate summary
      - name: Adding job summery
        run: |
          echo "### BUILD is okay! :rocket:" > $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "- building took... some minutes" >> $GITHUB_STEP_SUMMARY

  # TODO: Auto merge and delete branch
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Merging PR
        uses: KeisukeYamashita/auto-pull-request-merge@v1.0.6
        with:
          intervalSeconds: 10
          timeoutSeconds: 30

  # cleanup:
  #   runs-on: ubuntu-latest
  #   needs: [build, auto-merge]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: delete branch
  #       uses: SvanBoxel/delete-merged-branch@main
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
