name: Continous Integration

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test-build-merge:
    if: ${{ github.repository == 'ash1khan/digital-garden'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      # TODO: rules not implemented yet
      - name: Running Linting and formatting rules
        run: echo "run formatter and lint for all files"

        # TODO: test not implemented yet
      - name: Running test
        run: echo "Testing.."

      - name: Ensuring Astro builds with bun
        run: bun run build

      - name: Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
