# TODO:
# - on push to editorial branch will check linting of all md files
#  - and create a pr to main branch for merging

# on pull request in main branch
# - run test and build checks
# - merge
# - close pull request
name: Continous Integration

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test-and-build:
    if: ${{ github.repository == 'ash1khan/digital-garden'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node and pnpm
        uses: dafnik/setup-node-pnpm@v1
        with:
          node: 18
          pnpm: 8
          install: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Check types and style
        run: pnpm run check

      # - name: Test
      #   run: npm test

      - name: Ensure Astro builds
        run: pnpm run build
