name: Continous Integration

on: workflow_dispatch
#  pull_request:
#    branches:
#      - 'main'

jobs:
  setup:
    if: ${{ github.repository == 'ash1khan/digital-garden'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Get bun version
        id: bun
        run: |
          echo "::set-output name=version::$(bun --version)"
        
      - name: Set caching
        uses: actions/cache@3.3.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/bun.lockb') }}-${{ steps.bun.outputs.version }}
    
      - name: Install dependencies
        run: bun install
  
  lint-test-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      
      # TODO: rules not implemented yet
      - name: Running Linting and formatting rules
        run: echo "run formatter and lint for all files"

        # TODO: test not implemented yet
      - name: Running test
        run: echo "Testing.."

      - name: Ensuring Astro builds with bun
        run: bun run build

#      - name: Merge
#        uses: KeisukeYamashita/auto-pull-request-merge@v1.0.6
#        with:
#          intervalSeconds: 10
#          timeoutSeconds: 30
