# TODO:
# - on push to editorial branch will check linting of all md files
#  - and create a pr to main branch for merging

# on pull request in main branch
# - run test and build checks
# - merge
# - close pull request
name: Continous Integration

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test-and-build:
    if: ${{ github.repository == 'ash1khan/digital-garden'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        
      # TODO: test and lint process here
      # - name: Test
      #   run: npm test

      - name: Ensure Astro builds with bun
        run: bun run build


     

