name: Dev branch workflow

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    if: ${{ github.repository == 'ash1khan/digital-garden'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Get bun version
        id: bun
        run: |
          echo "version=$(bun --version)" >> "$GITHUB_OUTPUT"

      - name: Set caching
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/bun.lockb') }}-${{ steps.bun.outputs.version }}

      - name: Install dependencies
        run: bun install

      # TODO: rules not implemented yet
      - name: Running Linting and formatting rules
        run: echo "run formatter and lint for all files"

      # TODO: test not implemented yet
      - name: Running test
        run: echo "Testing.. with bun..."

      - name: Creating pull request
        run: gh pr create -B ${{ github.base_ref }} -H ${{ github.ref_name }} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
